### ISSUE TITLE
Disabling "Stack Overrun checking" in RTX_config.h leads to linker error "L6218E: Undefined symbol osRtxThreadStackCheck (referred from irq_armv7m.o)."

### ISSUE THREAD

**Issue by chentang16** [ARM-software/CMSIS-RTX#30]
The line 142 of irq_armv7m.S of CMSIS v6.0.0 pack uses osRtxThreadStackCheck without checking if the option "Stack Overrun checking" in RTX_config.h is enabled or not.
Other irq_armvxx.S may be also affected.

**Comment by JonatanAntoni** [comment]
Hi Chen,

I can see the `#ifdef RTX_STACK_CHECK` here
https://github.com/ARM-software/CMSIS-RTX/blob/7b056a242e98587b66eb7c1c3a73ff2ab6cb0539/Source/GCC/irq_armv7m.S#L130-L142

Can you provide more details about how to reproduce your link issue?

**Comment by chentang16** [comment]
Hi Jonatan,
you are right. I have overlooked that part. irq_armv7m.S is correct.
As I just show you in person, this is rather a Keil MDK µVision IDE problem.
The way to reproduce this issue:
1) Building an existing CMSIS-RTOS blinky example with the "Stack overrun checking" option enabled once. 
2) Disabling the "Stack overrun checking" option
3) Click Build, instead of "Rebuild", the linker error above will occur.

In this case actually MDK µVision failed detecting the change on RTX_Config.h should lead to a rebuild of irq_armv7m.S module.

Making a complete "Rebuild" of the project can resolve the linker error above.

Thus, closing this issue
