### ISSUE TITLE
Why can rtx_mutex only be released by the "owner" thread?

### ISSUE THREAD

**Issue by IngmarPaetzold** [ARM-software/CMSIS-RTX#34]
In my design, a certain kind of message is serialized (=only one processing at a time) with a mutex. The receiver thread shall (try to) acquire the mutex, give the message to processing, which puts it to a queue later on.
The transmitter thread will eventually pick it from the queue and send the response, and _then_ allow another loop by releasing the mutex.
However, only the owner thread can release a mutex:

https://github.com/ARM-software/CMSIS_5/blob/837ed048639cb9296e1a96a5e10170d83972d8ee/CMSIS/RTOS2/RTX/Source/rtx_mutex.c#L277-L282

```
  // Check if running Thread is not the owner
  if (mutex->owner_thread != thread) {
    EvrRtxMutexError(mutex, osRtxErrorMutexNotOwned);
    //lint -e{904} "Return statement before end of function" [MISRA Note 1]
    return osErrorResource;
  }
```

I could basically use **event flags** as well for that purpose, but a **mutex** seemed to carry the right _semantics_ for this purpose (= locking a resource). Why is the mutex behavior that strict (i.e. only to be released by owner)?

**Comment by JonatanAntoni** [comment]
Hi @IngmarPaetzold,

Thanks for reaching out to us. Please note that I transferred your issue over here to RTX's new home.

A mutex is actually defined exactly this way. It is used to protect a singleton resource. I.e., some thread aiming to access a singleton resource must only proceed after successfully acquiring the mutex. Once the thread finished using the resource it must released the mutex. It would not make any sense if a mutex acquired by one thread is released by a totally different thread. 

Did you consider using a semaphore instead? Counting semaphores are exactly made for such use cases. I.e., one thread can provide tokens by releasing the semaphore while another thread can consume them by acquiring the semaphore.

But perhaps you don't even need this level of additional complexity. If I understand correctly, the message queue has only one message slot. So, if the receiver thread tries to put another message to the queue this can block unless the transmitter removes the first message freeing up the single message slot.

**Comment by IngmarPaetzold** [comment]
Hi @JonatanAntoni,
in my understanding, a mutex was basically the same as a semaphore but explicitly with one token. But surely I can try a semaphore with count 1, since I was not aware that _mixed-thread operation_ is kind of a semantic property of a semaphore, but not of a mutex. "Token" is exactly the idea I need. As I see in semaphore's code, there is no such thread owner check 😊.

My workflow is a bit more complex, I had simplified it above:
The (response) queue has actually several slots and collects from different subsystems/threads, some blocking, some non-blocking, hence the asynchronous processing and communicating via queues. The needed singleton token shall ensure that for one particular type (=sub system), messages can only be processed at a time (whereas the other sub systems can).
In the rx thread, detecting which request type was received and aquiring the resource _on that type_ happens on a different level than releasing the resource much later in the tx thread _after the response has completely been sent_ .
All I need is actually a flag where tx thread notifies "Response is sent, resources no longer needed, you (rx) can aquire the next resource for that type". That's where I think about event flags for notification to reset the actual local lock/flag variable. But mutexes - and of course semaphores - have the charm that they not only _notify_ but they _are_ the flag.

So thanks for your answer and clarification on that important difference between mutex and semaphore concerning ownership. I'll give it a try.
