### ISSUE TITLE
Problems compiling library

### ISSUE THREAD

**Issue by SteMMo33** [ARM-software/CMSIS-RTX#43]
Hi all,
I'd like to compile the library for STM32MP135 micro.
After I added the library to the project, I have the following errors with GCC compiler:

- Building file: ../src/CMSISRTX/Source/GCC/irq_armv7m.S
Invoking: GNU Arm Cross Assembler
arm-none-eabi-gcc -mcpu=cortex-a7 -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -g3 -x assembler-with-cpp -I"C:\Progetti\dbTechnologies\testSTM32\testSTM32_CMSIS_RTOS2\src\CMSISRTX\Include" -I"C:\Progetti\dbTechnologies\testSTM32\testSTM32_CMSIS_RTOS2\src\CMSISRTX\Config" -MMD -MP -MF"src/CMSISRTX/Source/GCC/irq_armv7m.d" -MT"src/CMSISRTX/Source/GCC/irq_armv7m.o" -c -o "src/CMSISRTX/Source/GCC/irq_armv7m.o" "../src/CMSISRTX/Source/GCC/irq_armv7m.S"
../src/CMSISRTX/Source/GCC/irq_armv7m.S: Assembler messages:
../src/CMSISRTX/Source/GCC/irq_armv7m.S:68: Error: selected processor does not support requested special purpose register -- `mrseq r0,msp'
../src/CMSISRTX/Source/GCC/irq_armv7m.S:69: Error: selected processor does not support requested special purpose register -- `mrsne r0,psp'
../src/CMSISRTX/Source/GCC/irq_armv7m.S:71: Error: instruction not allowed in IT block -- `ldr r1,[r0,#24]'
../src/CMSISRTX/Source/GCC/irq_armv7m.S:72: Error: instruction not allowed in IT block -- `ldrb r1,[r1,#-2]'
../src/CMSISRTX/Source/GCC/irq_armv7m.S:205: Error: selected processor does not support requested special purpose register -- `msr psp,r0'
../src/CMSISRTX/Source/GCC/irq_armv7m.S:239: Error: selected processor does not support requested special purpose register -- `mrs r12,psp'
../src/CMSISRTX/Source/GCC/irq_armv7m.S:256: Error: selected processor does not support requested special purpose register -- `mrs r12,psp'
make: *** [src/CMSISRTX/Source/GCC/subdir.mk:20: src/CMSISRTX/Source/GCC/irq_armv7m.o] Error 1

- Building file: ../src/CMSISRTX/Source/GCC/irq_armv7a.S
Invoking: GNU Arm Cross Assembler
arm-none-eabi-gcc -mcpu=cortex-a7 -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -g3 -x assembler-with-cpp -I"C:\Progetti\dbTechnologies\testSTM32\testSTM32_CMSIS_RTOS2\src\CMSISRTX\Include" -I"C:\Progetti\dbTechnologies\testSTM32\testSTM32_CMSIS_RTOS2\src\CMSISRTX\Config" -MMD -MP -MF"src/CMSISRTX/Source/GCC/irq_armv7a.d" -MT"src/CMSISRTX/Source/GCC/irq_armv7a.o" -c -o "src/CMSISRTX/Source/GCC/irq_armv7a.o" "../src/CMSISRTX/Source/GCC/irq_armv7a.S"
../src/CMSISRTX/Source/GCC/irq_armv7a.S: Assembler messages:
../src/CMSISRTX/Source/GCC/irq_armv7a.S:379: Error: selected processor does not support `vmrs r2,fpscr' in ARM mode
../src/CMSISRTX/Source/GCC/irq_armv7a.S:382: Error: selected processor does not support `vstmdb r1!,{d0-d15}' in ARM mode
../src/CMSISRTX/Source/GCC/irq_armv7a.S:460: Error: selected processor does not support `vldmia lr!,{d0-d15}' in ARM mode
../src/CMSISRTX/Source/GCC/irq_armv7a.S:462: Error: selected processor does not support `vmsr fpscr,r2' in ARM mode
make: *** [src/CMSISRTX/Source/GCC/subdir.mk:23: src/CMSISRTX/Source/GCC/irq_armv7a.o] Error 1

Which is the correct source for my micro?
Thanks!

**Comment by VladimirUmek** [comment]
Hi,

irq_armv7a.S is the correct file. The RTX Library project was just updated and tested and works out of the box. Please open [RTX_Library.csolution.yml](https://github.com/ARM-software/CMSIS-RTX/blob/main/Library/RTX_Library.csolution.yml) in VS Code with Arm Keil Studio extensions and you should be ready to go.

**Comment by JonatanAntoni** [comment]
@SteMMo33,

Two observations in your log dump:

If you are targeting Cortex-A7 (Armv7-A), you can't compile the file `irq_armv7m.S` which is for Cortex-M (Armv7-M). Next, compiling `irq_armv7a.S` is the correct file but the compiler flags don't match. Firstly, this assembly file uses ARM instructions and can't be used with `-mthumb` (thumb mode). Secondly, you might need to set proper FPU flags for your device.

**Comment by SteMMo33** [comment]
Thanks,
the correct FPU flags are missing.
Thanks
