### ISSUE TITLE
What's the RTX lib for the Cortex-M33 with Non-DSP, SP_FPU, TrustZone?

### ISSUE THREAD

**Issue by SuperHeroAbner** [ARM-software/CMSIS-RTX#50]
There's RTX_V8MB for Non-DSP, Non-FPU, TrustZone.
There's RTX_V8MMF for DSP, FPU, TrustZone.
If there's cm33 core with Non-DSP, SP_FPU, TrustZone, there's no something like V8MBF. Should I use RTX_V8MB for it? For V8M Baseline, can FPU attribute be ignored?
According to [this](https://github.com/ARM-software/CMSIS-RTX/blob/main/ARM.CMSIS-RTX.pdsc#L79C1-L83C17), it seems V8MB is special for Cortex-M23.

**Comment by JonatanAntoni** [comment]
RTX pre-built libraries are only provided for a small set of configurations. If you need a specialized one for your target please build RTX5 from source code alongside your project.

The V8MMFN means Armv8-M Mainline (e.g, Cortex-M33) with floating point (single and double precision). There is also a V8MMN for Armv8-M Mainline without floating point. And V8MBN means Armv8-M Baseline (e.g., Cortex-M23) which has no support for floating point.

**Comment by SuperHeroAbner** [comment]
Hi @JonatanAntoni , thank you for your reply. I raise this ticket to confirm how to adapt RTX to our different chips with different cores.
History is I upgrade the CMSIS v5 to v6, also updating the DSP/NN/RTX to latest version together.
One chip with Cortex-M33 core(Non-DSP, SP_FPU, TrustZone) select the lib type RTX_V8MMF(DSP, FPU, TrustZone) in latest RTX 5.9.0, then iar/armclang compiler reports that DSP attribute error. It doesn't happen for the lib in CMSIS_5 v5.9.0 internal RTOS2/RTX. Then I tried RTX_V8MB lib, it can be used to build, but not sure whether running is OK. For this kind of case, do you suggest to use source code in project instead of lib? I just think that RTX_V8MB lib may be compatible to the V8MBF core.

**Comment by JonatanAntoni** [comment]
Hi @SuperHeroAbner,

True, the compiler attributes are an issue we don't have a solution for, yet. There are so many of them that providing pre-built libraries for all (commonly used) combinations does not scale. Hence, we decided to deprecate pre-built libraries and ask users to rely on the source modules. 

Cheers,
Jonatan

**Comment by SuperHeroAbner** [comment]
@JonatanAntoni Thank you for your patient answer.

**Comment by SuperHeroAbner** [comment]
Hi @JonatanAntoni , I'm trying to build with source code instead of library. Check the history CMSIS\RTOS2\RTX\Source\ARM\irq_xxx.s with irqRtxLib are all removed in this [commit ](https://github.com/ARM-software/CMSIS-RTX/commit/88b2d9d8fc94a06a16a77b25b3fed1dd1d085aa6#diff-567018077c109fd89f6bf7d8bee4bee32a45ce89173fd4884d8cac8874d6ba7d). But rtx_lib.c needs irqRtxLib. I want to know how to build RTX5 source code with ARM compiler 6.

**Comment by JonatanAntoni** [comment]
Hi @SuperHeroAbner,

I guess you already figured out that both, Arm Compiler and GCC, are using the same assembly language and thus we share a single set of files. As @RobertRostohar already explained in #51 this should not cause any compilation issues once configured properly.

Please provide more details about how you are building the source code and what issues you are facing if you require more help. Using an RTE-aware build environment (e.g., uVision or CMSIS-Build/Csolution) should automatically pick the right files from the released pack and run compilation with proper settings.
