### ISSUE TITLE
Multiple definition for SVC_ContextSaveSP

### ISSUE THREAD

**Issue by SuperHeroAbner** [ARM-software/CMSIS-RTX#51]
Defined double SVC_ContextSaveSP in all irq_xxx.S file.
For example:
https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L206
https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L160

**Comment by RobertRostohar** [comment]
The mentioned module uses conditions and the two labels SVC_ContextSaveSP are exclusive and only defined once depending on the 'RTX_STACK_CHECK' defintion.

`#ifdef RTX_STACK_CHECK` https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L152

`SVC_ContextSaveSP:` https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L160

`#else` https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L199

`SVC_ContextSaveSP:` https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L206

` #endif // RTX_STACK_CHECK ` https://github.com/ARM-software/CMSIS-RTX/blob/main/Source/GCC/irq_armv8mml.S#L209

**Comment by SuperHeroAbner** [comment]
@RobertRostohar Sorry maybe I touched something results in this. It's OK now.
